name: adlproject
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - cython=0.29.25
  - numpy=1.21.2
  - networkx=2.6.3
  - pyrr=0.10.3
  - pyyaml=6.0
  - python=3.8.12
  - pytorch=1.10.1
  - torchvision=0.11.2
  - pip=21.2.4
  - pillow=8.4.0
  - tqdm=4.62.3
  - trimesh=3.9.39
  - matplotlib=3.3.2
  - wxpython=4.1.1
  - seaborn=0.12.1
  - scipy=1.7.3
  - conda-forge::torchinfo=1.7.1
  - conda-forge::scikit-image=0.19.3
  - pip:
    - glcontext==2.3.4
    - moderngl==5.6.4
    - plyfile==0.7.4
    - shapely==1.8.0
    - simple-3dviz==0.4.0
    - pytorch-lightning==1.8.4.post0
    - pytorch-fast-transformers==0.4.0
    - pyglet==2.0.2.1
